### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by larsonjj** [darknoon/sketchapp-json-plugin#5]
Hey @darknoon,

Could you cut a new NPM release for this package? Would be great to get access to the latest changes in `master`. If you add me as an NPM collaborator, I could do it as well.

Let me know what you think. Thanks!

**Comment by darknoon** [comment]
@larsonjj sure, I will do it now. is it a .x or .x.x releaese?

**Comment by larsonjj** [comment]
Awesome! I would say its fair to bump it to `v0.1.0`

**Comment by darknoon** [comment]
Done!
