### ISSUE TITLE
Fix: New version

### ISSUE THREAD

**Issue by larsonjj** [darknoon/sketchapp-json-plugin#8]
Hey @darknoon,

Looks like `v0.1.1` didn't have a `npm run build` script run before it was published? Still seeing the old `v0.1.0` code within the `lib/` folder. Would you be able to double check and push a new build if that's the case?

Sorry to be a bother, just trying to get this in working order.

Thanks!

**Comment by darknoon** [comment]
@larsonjj do you have any idea how that would happen? I am expecting `prepublish` to activate with `yarn publish`.

I have been running `yarn pack` to test and unzip it to check that there are built files.

Maybe this is the issue? https://github.com/yarnpkg/yarn/issues/1671

Happy to help, but if I do the same steps again we may see the same result.

**Comment by larsonjj** [comment]
Oh weird, didn't know there was an existing issue with it. And yeah, `yarn publish` should run `prepublish`, otherwise that's a super annoying bug.

Maybe you could try `npm run build` and then `npm publish` for `v0.1.2` just to see if that works?

**Comment by darknoon** [comment]
Ok, I ran publish again which should have rebuilt it.

```

~/Code/Sketch/sketchapp-json-plugin (master u+2) $ npm publish

> sketchapp-json-plugin@0.1.2 prepare .
> npm run build


> sketchapp-json-plugin@0.1.2 build /Users/andrew/Code/Sketch/sketchapp-json-plugin
> babel src/ -d lib/

src/generateID.js -> lib/generateID.js
src/index.js -> lib/index.js

> sketchapp-json-plugin@0.1.2 prepack .
> echo 'working around yarn bug'; yarn run prepare

working around yarn bug
yarn run v1.1.0
$ npm run build

> sketchapp-json-plugin@0.1.2 build /Users/andrew/Code/Sketch/sketchapp-json-plugin
> babel src/ -d lib/

src/generateID.js -> lib/generateID.js
src/index.js -> lib/index.js
✨  Done in 0.97s.
+ sketchapp-json-plugin@0.1.2
~/Code/Sketch/sketchapp-json-plugin (master u+2) $ git push
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 612 bytes | 306.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 2 local objects.
To github.com:darknoon/sketchapp-json-plugin.git
   8d2e7df..18c0310  master -> master
```
